[project]
name = "retracesoftware_stream"
version = "0.1.23"
license = {text = "Apache-2.0"}
dependencies = []
#dependencies = ["retracesoftware_functional", "retracesoftware_utils"]

[build-system]
requires = ["meson-python>=0.15.0", "meson>=1.10", "ninja"]
build-backend = "mesonpy"