name: Release on Tag

on:
  push:
    tags:
      - '[v0-9]*.[0-9]*.[0-9]*'
jobs:
  build-release:
    uses: retracesoftware/.github/.github/workflows/release.yml@main
    with:
      package_name: "retracesoftware_stream"
      release_tag: ${{ github.ref_name }}
      build_debug: false
    secrets: inherit

  build-debug:
    uses: retracesoftware/.github/.github/workflows/release.yml@main
    with:
      package_name: "retracesoftware_stream_debug"
      release_tag: ${{ github.ref_name }}
      build_debug: true
    secrets: inherit
  
  publish-pypi:
    needs: [build-release, build-debug]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write # Required for OIDC/Trusted Publishing
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: "*-wheels"
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
